#.travis.yml

language: node_js
node_js:
  - "7.4"

branches:
  only:
    - master

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli
  - npm install
  - ng build

script:
  - ng lint
  - ng test --watch false
  - ng e2e

notifications:
  email:
    recipients:
      - stefani.gerber@politools.net
    on_success: never # default: change
    on_failure: never # default: always
